### PR TITLE
Need to port remaining examples, like done with tests and fszmq

### LINKED ISSUE #145: Consider supporting .Net core
https://icanhasdot.net/result?github=logary~2Flogary

### PR DESCRIPTION
**Pull request by haf**
Can you take it from here?

```
------------------------------------------------------------
~/dev/fszmq/tests/fszmq.tests(feature/netcore*) » dotnet run --framework netcoreapp2.0           h@catamorphism
Microsoft (R) Build Engine version 15.6.84.34536 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 48.36 ms for /Users/h/dev/fszmq/src/fszmq/fszmq.fsproj.
  Restore completed in 51.58 ms for /Users/h/dev/fszmq/tests/fszmq.tests/fszmq.tests.fsproj.
[20:40:02 INF] EXPECTO? Running tests... <Expecto>
Ok, passed 100 tests.
Ok, passed 100 tests.
Ok, passed 100 tests.
Ok, passed 100 tests.
[20:40:02 INF] EXPECTO! 72 tests run in 00:00:00.4004750 for miscellaneous – 65 passed, 7 ignored, 0 failed, 0 errored. ᕙ໒( ˵ ಠ ╭͜ʖ╮ ಠೃ ˵ )७ᕗ <Expecto>
```

Fixes #145 

https://twitter.com/henrikfeldt/status/990307054958075904

https://github.com/Microsoft/msbuild/issues/2468#issuecomment-324719212

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
Why Expecto? NUnit is not supported on .NET Core?

**Comment by vasily-kirichenko** [comment]
Expecto is not supported by Rider, it's a big cons.

**Comment by pblasucci** [comment]
@haf thanks for this. I realize it's long overdue that we move to .NET Standard 2.

However, I'm really _not_ comfortable with the way multiple concerns have been complected in this pull request. Can you please break out the testing framework changes (from NUnit to Expecto) to a separate pull request? Once that's done, we can move ahead with .NET Standard support. And give the topic of testing framework the attention is deserves. As things stand now, there's just too much going on.

Thanks again.  :-)

**Comment by haf** [comment]
Hi @pblasucci 

What you're asking for is easy to do in git yourself; you can copy and paste this:

```
cd fszmq
git pull --no-commit https://github.com/haf/fs-zmq feature/netcore
git checkout -- tests/fszmq.tests/Messages.fs tests/fszmq.tests/Miscellany.fs  tests/fszmq.tests/SocketOptions.fs tests/fszmq.tests/paket.references
rm tests/fszmq.tests/Program.fs
```

I don't see why we have to dance to @vasily-kirichenko's music. He's playing it loud and it doesn't sound very nice.

**Comment by vasily-kirichenko** [comment]
@haf be honest and people will love you.

**Comment by haf** [comment]
Ping @pblasucci

**Comment by pblasucci** [comment]
@haf I'm planning to pick this up and run with it -- but I haven't had time yet. Maybe in the next 3-5 days? I hope to find the time... but no promises.  :-(

**Comment by haf** [comment]
Absolutely. I'm working on https://github.com/logary/logary/issues/322 in the mean while; at the end of these two PRs we'll have a high-performance cross-platform cloud-native super-awesome log shipping framework ;)

**Comment by pblasucci** [comment]
OK, so... it's not done yet, but I've made good progress on this. See here: https://github.com/pblasucci/fszmq/tree/upgrade-netstandard2.

I've basically got it sorted on Windows. But I've not sorted the nuget package yet. I also need to verify that it works correctly on OS X. And I want to update the README and CONTRIBUTING docs. But it'll likely be a few days before I get to that.

Also, in the slightly longer term, I want to re-think the documentation process (it won't run on .NET Core, at the moment because FSI). But I'm going to tackle that in a separate PR.

**Pull request merged**
